-- Auto-generated by O.S.T Manager Script
addappid(1097150)
addappid(1097151, 1, "243e7ffcd6bbd15f3976f648f7d851f975219f7a995ffb32e404e7a94e84dae9")
addappid(1097161, 1, "c05cfb55ba077959101631121dc9f703d649e5877d74b04966d2675f7ddcdf3f")
