-- Auto-generated by O.S.T Manager Script
addappid(1190460)
addappid(1190461, 1, "ba4c72812b801fa2b777bbbb0e3bc51cdd4d5a96e9684b8d267d6273eb9d9552")
addappid(1190470, 1, "4197f91760ac16404b9fcef6851a187b50398e15d6f00b1bc222c9d273b34791")
