-- Auto-generated by O.S.T Manager Bot
addappid(3489700)
addappid(3489701, 1, "2266ca31f6f2666ebe75906201e72f9398694030ff1c8214aacebcf74dc94ee3")
addappid(3489721, 1, "ddfff11d1b7b66a2b49cf70b5a5f78b74c9ab08415ac999ab01c3de6ee7d90d8")
